### ISSUE TITLE
Code Lens request is not sent after document edit

### ISSUE THREAD

**Issue by Vadimtro** [eclipse/lsp4e#385] opened 2023-01-20 00:56 UTC
Compared to vscode, eclipse client has the following issues.

1. `textDocument/codeLens`is sent only once after `textDocument/didOpen`, and is not sent after subsequent document edits. I have attempted to workaround it as follows.
2. Sending request  [workspace/codeLens/refresh](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeLens_refresh) to manually trigger the CodeLens refresh stumbles upon https://github.com/eclipse/lsp4j/blob/e28b2f445e59bd78674e30f13c8c64a74f550603/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/services/LanguageClient.java#L208

**Comment by Vadimtro** [comment] 2023-01-20 01:14
The 3rd issue -- didOpen fired after codeLens -- seems also to be a bug, but I can work it around. The log:

[2023-01-19T17:09:19.151342-08:00] LSP4E to lsp.sql.server:
{"jsonrpc":"2.0","id":"2","method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql"}}}
[2023-01-19T17:09:19.**151936**-08:00] LSP4E to lsp.sql.server:
Content-Length: 168


[2023-01-19T17:09:19.161231-08:00] LSP4E to lsp.sql.server:
{"jsonrpc":"2.0","id":"3","method":"textDocument/documentColor","params":{"textDocument":{"uri":"file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql"}}}
[2023-01-19T17:09:19.166094-08:00] LSP4E to lsp.sql.server:
Content-Length: 386


[2023-01-19T17:09:19.**166426**-08:00] LSP4E to lsp.sql.server:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql","languageId":"sql","version":1,"text":"connect ...

**Comment by rubenporras** [comment] 2023-01-20 09:24
I think that we can solve the issue once https://github.com/eclipse/lsp4e/pull/344 or https://github.com/eclipse/lsp4e/pull/347 is merged

**Comment by Vadimtro** [comment] 2023-01-20 21:03
@rubenporras #344 would fix message ordering, but what about LSP requests triggered by `textDocument/didChange`? Vscode sends a lot of other messages accompanying `textDocument/didChange`, including `textDocument/codeLens`. Can I register eclipse editor listener, which would send those missing messages as a workaround?

**Comment by mickaelistria** [comment] 2023-01-23 17:55
Please try installing https://download.eclipse.org/lsp4e/snapshots/ and report whether the issue is still present.

**Comment by Vadimtro** [comment] 2023-01-23 18:42
I see the message ordering fixed. I don't see the CodeLens triggered by the edit. Log:

[```
2023-01-23T10:32:31.901380-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":2563,"rootPath":"/Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/“…

[2023-01-23T10:32:36.203545-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","id":1,"result":{"capabilities": { "completionProvider": {"triggerCharacters":["."],"hoverProvider":true} , …

[2023-01-23T10:32:36.212980-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","method":"initialized","params":{}}
[2023-01-23T10:32:36.228409-08:00] LSP4E to  sql.server:
Content-Length: 381


[2023-01-23T10:32:36.232428-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql","languageId":"sql","version":1,"text”:…

[2023-01-23T10:32:36.249392-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","id":"2","method":"textDocument/documentColor”…

[2023-01-23T10:32:36.262179-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","id":"3","method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql"}}}

[2023-01-23T10:32:40.082843-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{  "uri": "file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql", "diagnostics": []}}

[2023-01-23T10:32:40.163872-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","id":2,"result":[{ "range": { "start": {"line":0,"character":0}, "end": {"line":0,"character":1} }, "color": {"red":0.0,"green":0.0,"blue":0.0,"alpha":0.5} },{ "range": { "start": {"line":2,"character":0}, "end": {"line":2,"character":1} }, "color": {"red":0.0,"green":0.0,"blue":0.0,"alpha":0.5} }]}

[2023-01-23T10:32:40.166066-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","id":3,"result":[{ "range": { "start": {"line":0,"character":0}, "end": {"line":0,"character":57} }, "command": { "title": "Establish Connection”…
[2023-01-23T10:32:51.660095-08:00] LSP4E to  sql.server:
Content-Length: 384


[2023-01-23T10:32:51.660654-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":2,"uri":"file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql"},"contentChanges":[{"text":"connect scott/tiger@\"jdbc:oracle:thin:@localhost:1521/xe\"\n\nconnect hr/oracle@\"jdbc:oracle:thin:@dbtools-dev.oraclecorp.com:2323/DB23P\"\n\nSELECT /*csv*/\n    *\nFRO\n    countries;"}]}}

[2023-01-23T10:32:53.889826-08:00] LSP4E to  sql.server:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{  "uri": "file:///Users/VTROPASH/Documents/Eclipse_SQL_LSP_workspace/test.sql", "diagnostics": [{ "range": { "start": {"line":5,"character":6}, "end": {"line":5,"character":9} }, "message": "Syntax Error at line 6, column 6\n\n\n    *\n      ^^^\n\nExpected: 'FROM',", "severity": 1 }]}}

```

**Comment by Vadimtro** [comment] 2023-01-23 19:33
To remove possible confusion, here is the timestamp of lsp4e jar version from p2 repository:
org.eclipse.lsp4e_0.16.0.202301231330.jar

**Comment by sebthom** [comment] 2023-01-24 21:40
> > I see the message ordering fixed. I don't see the CodeLens triggered by the edit
> 
> @sebthom it might be related to the removed reconcilier; maybe it was actually necessary? Do you think you can have a look soon?

I don't see how this is related. We were registering exactly the same class `org.eclipse.jface.text.codemining.CodeMiningReconciler` as second time. When I step debugged it, I could see that the second CodeMiningReconciler instance was actually not installed because of: https://github.com/eclipse-platform/eclipse.platform.text/blob/d04589f174cac85f45fd4418dfa6053cbc16caa9/org.eclipse.jface.text/src/org/eclipse/jface/text/codemining/CodeMiningReconciler.java#L56

**Comment by mickaelistria** [comment] 2023-01-25 12:35
@Vadimtro Can you reproduce this issue with eg XML files using Wild Web Developer? If yes, can you please share steps to reproduce it?

**Comment by mickaelistria** [comment] 2023-03-14 12:19
@Vadimtro many changes took place recently, including regarding orchestration of LS calls. Can you please give a try to latest snapshots and report whether it updates some aspects of this issue?

**Comment by sebthom** [comment] 2024-08-16 15:13
I cannot reproduce this issue with latest LSP4e release. `textDocument/codeLens` events are send after edits.

 Feel free to reopen if the issue persist.

**Closed by sebthom** 2024-08-16 15:13 UTC
