### ISSUE TITLE
MicroProfileGenerateOpenAPIOperation code action breaks developer workflow

### ISSUE THREAD

**Issue by Jotschi** [eclipse/lsp4e#939] opened 2024-03-01 07:57 UTC
When working with quickfixes the [MicroProfileGenerateOpenAPIOperation](https://github.com/eclipse/lsp4mp/blob/de6c6b96d164d2ada4fa87997381fac618482500/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java#L51) operation breaks the typical developer workflow.

![image](https://github.com/eclipse/lsp4e/assets/326605/66490813-4086-407e-beeb-e2aea1e26772)

Please make this operation configurable or remove it.

[Related SO issue](https://stackoverflow.com/questions/78080107/customize-eclipse-quickfix-popup?noredirect=1#comment137650729_78080107)

I report this issue here as suggested by @angelozerr  - https://github.com/eclipse/lsp4mp/issues/438

**Comment by mickaelistria** [comment] 2024-03-01 09:41
Looks like a duplicate of https://github.com/eclipse/lsp4e/issues/867

**Closed by mickaelistria** 2024-03-01 09:41 UTC
