### ISSUE TITLE
Undo operation fails to correctly restore text 

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lsp4e#178] opened 2022-07-07 10:38 UTC
When editing an element name, the Undo operation fails to correctly restore the text. Tested on XML/HTML LS Editors with WWD, 

Steps to reproduce:

- Create an XML or HTML file and open it in Generic Editor, for example:
```
<html>
	<body>
		<h1 class="test">
		</h1>
	</body>
</html>
```
- Place the text cursor after the name of tag `<body|>` (`"|"` char - shows the cursor position)
- Type-in some valid element name character or Paste some valid characters from the Clipboard into the current position. The element name is to be modified for both - the opening and the closing tag: 
```
<html>
	<bodyF>
		<h1 class="test">
		</h1>
	</bodyF>
</html>
```
- Press `Ctrl-Z` to undo the last modification. The result looks like the following: 
```
<html>
	<body
		<h1 class="test">
		</h1>
	</body>
</html>
```
(extra characters removed from the text: `F>` gets removed from the opening tag instead of removing just `F` character, the document structure gets broken as the result). 
- Pasting more than one character makes the `error` on `Undo` to be bigger (more extra characters resulted to be removed)

**Comment by mickaelistria** [comment] 2022-07-08 11:36
I can reproduce without pasting: from `<a></a>`, just type another char after the first `a` and linked edit turns it into eg `<ab></ab>`, Ctrl+Z; expected `<a></a>`, got `<a</a>`.
Do you think you can reproduce it in some automated test?

**Comment by mickaelistria** [comment] 2022-07-15 14:47
I fhink I found the cause: the undo text edit, when hitting Ctrl+Z is processed but the linked edit is still active. So the linkedEdit adds an extra event to remove some more chars. On undo, the linkedEdit should probably be ignored.

**Comment by mickaelistria** [comment] 2022-07-15 14:48
An interesting case is to reproduce is 
```
<a>
  <b></b>
</a>
```
if editing `a` and undoing immediately, file is corrupted (there are 3 TextEdits while undoing instead of 2)
When editing `a` and moving to `b` so linkedEdit ranges are not involved any more, then undoing is fine.

**Comment by vrubezhny** [comment] 2022-07-16 01:14
> I fhink I found the cause: the undo text edit, when hitting Ctrl+Z is processed but the linked edit is still active. So the linkedEdit adds an extra event to remove some more chars. On undo, the linkedEdit should probably be ignored.

I think you're right. It looks like exiting Linked Editing Mode on Ctrl-Z helps to prevent the appearance of extra characters removed/added by Undo operation. More is that it makes the Linked Editing Mode changes to be Undo-ed at once (1-2-3-etc. characters added to an element name will be removed by a single Undo operation from the "main" and "slave" elements).

 The PR demonstrating the fix: https://github.com/eclipse-platform/eclipse.platform.text/pull/58

**Closed** 2022-10-06 11:10 UTC
