### ISSUE TITLE
Long freezes in editing pom files due to hover

### ISSUE THREAD

**Issue by vogella** [eclipse/lsp4e#217] opened 2022-08-23 08:24 UTC
I get a > 6 seconds freeze during the editing of a pom file for tests with the following stacktrace:

```
Stack Trace
	at java.base/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
	at org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingAutoEditStrategy.customizeDocumentCommand(LSPLinkedEditingAutoEditStrategy.java:41)
	at org.eclipse.jface.text.TextViewer.customizeDocumentCommand(TextViewer.java:3702)
	at org.eclipse.jface.text.TextViewer.handleVerifyEvent(TextViewer.java:3744)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.handleVerifyEvent(ProjectionViewer.java:1250)
	at org.eclipse.jface.text.TextViewer$TextVerifyListener.verifyText(TextViewer.java:426)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:277)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7606)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8538)
	at org.eclipse.swt.custom.StyledText.paste(StyledText.java:7712)
	at org.eclipse.jface.text.TextViewer.paste(TextViewer.java:4016)
	at org.eclipse.jface.text.TextViewer.doOperation(TextViewer.java:3944)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:1064)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1468)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor$1.doOperation(ExtensionBasedTextEditor.java:109)
	at org.eclipse.ui.texteditor.TextOperationAction.lambda$0(TextOperationAction.java:130)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.texteditor.TextOperationAction.run(TextOperationAction.java:130)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatch

```

**Comment by mickaelistria** [comment] 2022-08-23 12:56
Do you have steps to reproduce? Particular m2e plugins verstiom. particular Ecllipse version. file content...?

**Comment by vogella** [comment] 2022-08-23 14:18
I can only reproduce in a client environment but 	at org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingAutoEditStrategy.customizeDocumentCommand(LSPLinkedEditingAutoEditStrategy.java:41) seems to call get which is blocking. Why not react once the completable future is done?

**Comment by mickaelistria** [comment] 2022-08-23 14:29
Because the auto-edit strategy returns an edit that's supposed to be merged with the user edit in the same TextEdit received by the IDE. The auto-edit has to be applied immediately, before users makes further edits.

**Comment by vrubezhny** [comment] 2023-01-11 17:18
@vogella @mickaelistria Sorry for intervening here, but...

What does this issue have to do with Hover? I don't see any Hover related code in the stacktrace provided...

**Comment by sebthom** [comment] 2023-01-14 22:46
The `LSPLinkedEditingAutoEditStrategy` class referenced in the stacktrace was removed from the code base as part of LSP4E 0.20.2 from March 2022. We are now at least six releases further. I would suggest to either provide a new stacktrace from a recent LSP4E release or close the issue.

**Comment by mickaelistria** [comment] 2023-01-15 09:55
Thanks @sebthom 
Let's close. @vogella and others, feel free to reopen with up-to-date details using latest release or snapshot if error still occurs.

**Closed by mickaelistria** 2023-01-15 09:55 UTC
