### ISSUE TITLE
Conflicting keybinding for Open Type

### ISSUE THREAD

**Issue by trancexpress** [eclipse/lsp4e#38] opened 2022-01-03 10:24 UTC
On Eclipse bugzilla the issue was: https://bugs.eclipse.org/bugs/show_bug.cgi?id=527785

A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@101eb529,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6a9b8f33,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

**Comment by garretwilson** [comment] 2023-01-05 12:46
I installed Eclipse EE 2022-12, and now when I try to find a Java class using `Ctrl+Shift+T`, I first get a menu asking if I want to "Go to Symbol in Workspace" or "Open Type". I can keep doing this over and over and it shows these conflicting mapped commands.

But oddly if I `Ctrl+Click` on a class to open another file, and then close the file going back to the original class source code, then `Ctrl+Shift+T` brings up "Open Type" as I would expect.

My error log shows

```
eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jface
Warning
Thu Jan 05 09:41:46 BRT 2023
Keybinding conflicts occurred.  They may interfere with normal accelerator operation.

eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jface
Warning
Thu Jan 05 09:41:46 BRT 2023
A conflict occurred for ALT+SHIFT+R:
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.edit.text.java.rename.element"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
		Rename the selected item,
		Category(org.eclipse.ui.category.file,File,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.rename"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jface
Warning
Thu Jan 05 09:41:46 BRT 2023
A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.navigate.open.type"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.lsp4e.symbolinworkspace"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
```

This bug is very problematic, as "Open Type" via `Ctrl+Shift+T` is one of my most-used commands.

**Comment by mickaelistria** [comment] 2023-01-06 10:50
Hello,

What file is open while you're trying Ctrl+Shift+T ?

**Comment by garretwilson** [comment] 2023-01-06 12:26
> What file is open while you're trying Ctrl+Shift+T ?

Just a normal Java source file.

**Comment by mickaelistria** [comment] 2023-01-06 12:46
OK. And is the Java source opened in the Java editor or in the Generic Editor? Do you have other plugins installed that are supposed to provide Java assistance? The Ctrl+Shift+T handler from LSP4E shouldn't be participating at all unless there is a language server bound to .java files, and IIRC there is not such one by default in Eclipse packages.

**Comment by garretwilson** [comment] 2023-01-06 12:50
> And is the Java source opened in the Java editor or in the Generic Editor?

The Java editor. And once the `Ctrl+Click` workaround happens, the same editor works again—like it has worked for like 20 years.

> Do you have other plugins installed that are supposed to provide Java assistance? 

I am using the exact EE distribution for 2022-12: [`eclipse-jee-2022-12-R-win32-x86_64.zip`](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-12/R/eclipse-jee-2022-12-R-win32-x86_64.zip). I don't believe I have installed any other plugins.

> The Ctrl+Shift+T handler from LSP4E shouldn't be participating at all unless there is a language server bound to .java files, and IIRC there is not such one by default in Eclipse packages.

Exactly. And that's why this is a bug.

**Comment by miklossy** [comment] 2023-01-09 14:38
Maybe a duplicate of https://github.com/eclipse/lsp4e/issues/164

**Comment by mickaelistria** [comment] 2023-01-09 14:49
> Maybe a duplicate of https://github.com/eclipse/lsp4e/issues/164

Not exactly. #164 is about a logged message (which should be removed in Platform by the way); Here there is another preliminary issue: what does configure LSP4E to be active on .java files; this is not much intended in the EPP packages as far as I know. The EPP package needs to be investigated first.

**Comment by lukeu** [comment] 2023-01-18 22:52
Saw this for the first time, after Eclipse upgraded itself to:

    Eclipse IDE for Eclipse Committers (includes Incubating components)
    Version: 2023-03 M1 (4.27.0 M1)

I can confirm the previous comment that the issue returns after a restart, with only a few .java files open (in the Java Editor). I found that Ctrl+click on an identifier (to navigate) resolves the issue immediately. (After which, Ctrl+Shift+T shows the open-type dialog as expected.)

**Comment by mickaelistria** [comment] 2023-01-19 19:39
What is the language server that is bound to Java files and contributes to Ctrl+Shift+T?

**Comment by lukeu** [comment] 2023-01-19 21:52
I've never deliberately started any language-server-backed-editor. (Yet - very interested in that though.) How would I find out?

**Comment by mickaelistria** [comment] 2023-01-20 11:51
> I've never deliberately started any language-server-backed-editor. (Yet - very interested in that though.) How would I find out?

I don't think it would be deliberate. Can you please share the content of the "Language Servers" preference page and see what is bound to Java files?

**Comment by lukeu** [comment] 2023-01-20 20:59
Hope this helps:
![image](https://user-images.githubusercontent.com/2722420/213803956-cf70ab70-b52a-4597-8759-a60eebdf95b8.png)

**Comment by papegaaij** [comment] 2023-01-23 08:49
It's not just `Open type` that's affected by this issue. I just noticed that `Rename` (Alt+Shift+r) doesn't work either. After Ctrl-clicking on any Java identifier, it works again.

**Comment by wrayphi** [comment] 2023-01-30 15:33
recently upgraded to 20221201-1913 and seeing same issues for both (Alt + Shift + R) and (Ctrl + Shift + T). Thanks for tip on ctrl clicking which clears it up temporarily

**Comment by kopfarzt** [comment] 2023-02-01 08:08
Same here, Alt-Shift-R and Ctrl-Shift-T do not work.

Version: 2022-12 (4.26.0)
Build id: 20221201-1913

@lukeu 
![image](https://user-images.githubusercontent.com/3287742/215986153-5e076c04-7b15-4637-a342-80971dbf4b06.png)

**Comment by mickaelistria** [comment] 2023-02-01 15:11
I tried the following:
* Downloaded Eclipse IDE for Java Developers 2022-12 from https://www.eclipse.org/downloads/eclipse-packages/ ; directly the .tar.gz for Linux, without the installer
* Created a new Java project
* Created a new class in this Java project
* Hit Ctrl+Shift+T => got the "Open Type" dialog without preliminary choice.

So I cannot reproduce the issue. Can someone provide detailed steps to reproduce, from a fresh download and unzip of the package?

**Comment by lukeu** [comment] 2023-02-04 10:09
> Can someone provide detailed steps to reproduce, from a fresh download and unzip of the package?
Same steps as yours, but using the 2022-12 IDE For Committers Edition, produces it. (In also a new workspace.)

**Comment by bgaraude** [comment] 2023-02-13 08:17
> So I cannot reproduce the issue. Can someone provide detailed steps to reproduce, from a fresh download and unzip of the package?

I did the very same than you did, except it was with the windows version:
* Download the windows eclipse-java-2022-12-R-win32-x86_64.zip package from https://www.eclipse.org/downloads/packages/
* Created a new Java project
* Created a new Java class named Foo
* Hit Ctrl+Shift+T => got the below popup in lower right corner (cf attached picture), and no dialog.



![open-type](https://user-images.githubusercontent.com/1769048/218405321-7f11ceec-5dda-4648-96a6-20568dce9ac0.png)

**Comment by jukzi** [comment] 2023-03-07 10:23
> So I cannot reproduce the issue. Can someone provide detailed steps to reproduce, from a fresh download and unzip of the package?

OOmp Eclipse (https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md). When you click ctrl+shift+T the first time the dialog appears. After selecting Open Type once, it does not appear anymore.

**Comment by mickaelistria** [comment] 2023-03-14 20:19
I'm closing this in LSP4E, it's more properly actionable on JDT end: https://github.com/eclipse-platform/eclipse.platform.ui/issues/513#issuecomment-1468778600

**Closed by mickaelistria** 2023-03-14 20:19 UTC

**Comment by mickaelistria** [comment] 2023-03-15 07:24
Note that additionally to having a proposal to ensure the JDT editor uses the right command for the binding, LSP4E also has received many improvements, currently only available in snapshots, that can have a postiive impact on this issue. So please try installing LSP4E snapshots. A release may take place later this week or next week.
